<?php

namespace vTechSolution\Bundle\QuickBookBundle\Repository;

/**
 * Quickbook_TokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Quickbook_TokenRepository extends \Doctrine\ORM\EntityRepository
{
}
